version: 1

formatters:
  simple:
    format: '%(name)16s - %(levelname)5s - %(message)s'
  plain:
    format: '%(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    #formatter: simple
    formatter: plain
    stream: ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: plain
    level: DEBUG
    filename: exec.log
    backupCount: 5
    maxBytes: 15000
  grid:
    class : logging.handlers.RotatingFileHandler
    formatter: plain
    level: DEBUG
    filename: grid.log
    backupCount: 5
    maxBytes: 15000

loggers:
  classispecies:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  result_to_file:
    level: DEBUG
    handlers: [file]
  result_to_grid:
    level: DEBUG
    handlers: [grid]