version: 1

formatters:
  simple:
    format: '%(name)16s - %(levelname)5s - %(message)s'
  plain:
    format: '%(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    #formatter: simple
    formatter: plain
    stream: ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: plain
    level: DEBUG
    filename: outputs/logs/exec.log
    backupCount: 5
    maxBytes: 15000
  grid:
    class : logging.handlers.RotatingFileHandler
    formatter: plain
    level: DEBUG
    filename: outputs/logs/grid.log
    backupCount: 5
    maxBytes: 15000
  f1:
    class: logging.handlers.RotatingFileHandler
    formatter: plain
    level: DEBUG
    filename: outputs/logs/f1.log
    backupCount: 5
    maxBytes: 15000
  confusion:
    class: logging.handlers.RotatingFileHandler
    formatter: plain
    level: DEBUG
    filename: outputs/logs/confusion.log
    backupCount: 5
    maxBytes: 1000000
loggers:
  classispecies:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  result_to_file:
    level: DEBUG
    handlers: [file]
  result_to_grid:
    level: DEBUG
    handlers: [grid]
  f1:
    level: DEBUG
    handlers: [f1]
    propagate: no
  confusion:
    level: DEBUG
    handlers: [confusion]
    propagate: no